### ISSUE TITLE
test VIN

### ISSUE THREAD

**Issue by dwunsch** [todvora/policeapi#1]
it would be nice to have at least one VIN of a car that is entered as stolen into the database for testing

**Comment by todvora** [comment]
Here is a list of lately discovered vehicles: https://pcr-tdvorak.rhcloud.com/list. Feel free to select some of them for your tests.

Please also note this package, which is extracted client code for querying police website, without any dependencies to presentation layer or webserver: https://www.npmjs.com/package/policecz-vehicles-client.

There is also a Go implementation, if you search for something simple and fast: https://github.com/todvora/gopoliceapi/blob/master/scraper.go

**Comment by dwunsch** [comment]
thank you very much!
